### ISSUE TITLE
feature request: ignore/filter some messages

### ISSUE THREAD

**Issue by dkrnl** [postcss/postcss-fail-on-warn#9]
via https://github.com/twbs/bootstrap/issues/36259 and [autoprefixer@10.4.6](https://github.com/postcss/autoprefixer/releases/tag/10.4.6)

**Comment by ai** [comment]
You can create a PostCSS plugin which will clean `result.warnings` from unnecessary warnings.

But you can also send PR with `ignore: RegExp | RegExp[]` option.
